version: '3.8'
services:
  metrics-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}

    container_name: metrics-api-dev
    labels:
      shipyard.route: /
    env_file:
      - environment/dev
    ports:
      - "8000:8000"
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - metrics
    command: /run_dev_server.sh

  postgresql:
    image: postgres:9.3
    platform: linux/amd64
    container_name: metrics-postgresql
    restart: always
    env_file:
      - environment/dev
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - metrics

  redis:
    image: redis:7
    platform: linux/amd64
    container_name: metrics-redis
    restart: always
    volumes:
   - redis_data:/data
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - metrics

networks:
  metrics:
    driver: bridge

volumes:
  postgresql_data:
  redis_data:
                               
